# Generated by Django 5.2.1 on 2025-07-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_timesheet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timesheet",
            name="task",
        ),
        migrations.AddField(
            model_name="timesheet",
            name="project",
            field=models.CharField(default="Misc Project", max_length=100),
            preserve_default=False,
        ),
    ]
